//This file was generated by a tool 2019-04-30T19:12:32.372Z, any changes will be overwrittenread readme.md in /assets folder on how to update this file
export interface BinMap { [key: string]: string; }

export const bins: BinMap = { bin0:"bin0.png" };

export type AssetId = "grass_tile4x"
    |"stone_tile4x";

export const resources = {
    "grass_tile4x": {
        "id": "grass_tile4x",
        "bin": "bin0",
        "origin": {},
        "binPosition": {
            "x": 0,
            "y": 0,
            "w": 72,
            "h": 112
        }
    },
    "stone_tile4x": {
        "id": "stone_tile4x",
        "bin": "bin0",
        "origin": {},
        "binPosition": {
            "x": 72,
            "y": 0,
            "w": 72,
            "h": 112
        }
    }
};